version: "3"
services:
  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 8080:8080
      - 443:443

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    restart: always
    ports:
      - 80:80
  # nginx:
  #   depends_on:
  #     - nginx_proxy
  #   image: nginx:alpine
  #   restart: always
